refactor: Use gin to replace mux
DropKit/DropKit-Adapter pull request #13
Opened 2020-09-03 05:02 UTC by HowJMay

2020-09-03 23:19 UTC, jserv commented
Since you are making non-trivial changes, there should be a solid and self-contained way to validate the change. Can you follow [golang-gin-realworld-example-app](https://github.com/gothinkster/golang-gin-realworld-example-app) and provide necessary tests?

2020-09-04 01:39 UTC, HowJMay commented
> Since you are making non-trivial changes, there should be a solid and self-contained way to validate the change. Can you follow [golang-gin-realworld-example-app](https://github.com/gothinkster/golang-gin-realworld-example-app) and provide necessary tests?

In this PR, I have provided a basic test for `/ping` to ensure the ability.

2020-09-04 08:33 UTC, HowJMay commented
@junwei0117 Had implemented a [demokit](https://github.com/DropKit/demokits) which can be used as a comprehensive test for the routing as well.

2020-09-04 09:30 UTC, jserv commented
> In this PR, I have provided a basic test for `/ping` to ensure the ability.

Good. Let's enable CI before merging this pull request.

2020-09-05 17:55 UTC, HowJMay commented
> > In this PR, I have provided a basic test for `/ping` to ensure the ability.
> 
> Good. Let's enable CI before merging this pull request.

I am trying to translate and simplify the demokit to python script, but it will still take around 200 lines of python code. Could I split the testing script to another PR?

2020-09-06 16:15 UTC, jserv commented on tests/index.ts
> +const DROPKIT_ENDPOINT = "http://localhost:5000";
Read configurations for test suite from specific file(s).

2020-09-06 16:15 UTC, jserv requested changes
Read test programs in Go as well.

2020-09-16 02:17 UTC, merged